---
about:
  template: marquee
html:
  includes:
    in_header: open-links-in-new-tab.js
editor: 
  markdown: 
    wrap: 90
---

# **Introduction**

Welcome to the **Mannheim Master in Management Analytics - Accounting Class of 2024**
practical application sessions. Over the next two days, we will delve into the application
of R and Excel to address prevalent business challenges, with a particular focus on
web-scraping. Our aim is to equip you with insights into the automation and optimization
of routine workflows.

While the sessions are designed in R, a foundational understanding of programming is
crucial. We will methodically break down the advanced techniques used in the code for
better comprehension.

# **Resources and Assistance**

Engage in guided in-class exercises throughout these sessions. This year, we're bolstered
by the support of Large Language Models (LLMs). I strongly advocate for the utilization of
these tools to amplify your learning experience. Here's a snapshot of some leading LLMs:

-   [**ChatGPT (3.5/4.0)**](https://chat.openai.com/): A distinguished tool in the AI
    domain.

-   [**Perplexity AI**](https://www.perplexity.ai/): Harnessing the GPT-4 framework, it
    offers native web-searching capabilities.

-   [**Google Bard**](https://bard.google.com/): A notable AI tool in the market.

-   [**Claude AI**](https://claude.ai/login): Accessible primarily in US/UK; VPN can
    provide broader access.

For effective prompting, consider:

-   [**PromptPerfect**](https://promptperfect.jina.ai/home): Enhance your prompting
    skills.

-   [**PromptoMania**](https://promptomania.com/): An AI-driven prompt generator.

**Disclaimer:**

LLMs may produce diverse results. Some might provide direct solutions, while others may
necessitate further adjustments. The primary goal is understanding, not necessarily
mastering every coding detail. The overarching principle is: **If it's effective, it's
right!**

# **Setting Up R and Rstudio**

R and RStudio installations are needed for our interactive exercises. The setup is
intuitive. Kindly follow the
[**instructions**](https://rstudio-education.github.io/hopr/starting.html) to install the
necessary components.

**Accessing the Code**

The codebase for our sessions is hosted on my GitHub page:
[**MatthiasUckert/RpMMA24**](https://github.com/MatthiasUckert/RpMMA24). You can either
fork the repository to your GitHub account or download the project directly.

# Table of Content

Navigate through the sessions using the links in this table or the drop-down menus atop
the page.

+---------------------+------------------------------------------------------------------+
| Day                 | Description                                                      |
+:====================+:=================================================================+
| Day 1               | [**Building an Excel Business Case**](exercises/day1.qmd)        |
|                     |                                                                  |
|                     | Construct a concise business case in Excel, evaluating a         |
|                     | business decisions using metrics like the **Contribution         |
|                     | Margin**                                                         |
+---------------------+------------------------------------------------------------------+
| Day 2               | [**Getting Data from the Web**](exercises/day2.qmd)              |
|                     |                                                                  |
|                     | Master web scraping in scenarios with and without an API.        |
|                     |                                                                  |
|                     | -   <http://www.annualreport.com/>                               |
|                     |                                                                  |
|                     | -   <https://www.sec.gov/edgar>                                  |
+---------------------+------------------------------------------------------------------+

------------------------------------------------------------------------------------------

# Interesting Readings

-   **Advanced R: <https://adv-r.hadley.nz/>**
-   **R for Data Science: <https://r4ds.had.co.nz/>**
-   **Hands-On Programming With R:** <https://rstudio-education.github.io/hopr/>
