---
title: "Day 0 - Making Sure Everything Works"
format: html
---

# Setting Up R and Rstudio

R and RStudio installations are needed for our interactive exercises. The setup is intuitive. Kindly follow the [**instructions**](https://rstudio-education.github.io/hopr/starting.html) to install the necessary components.

**Accessing the Code**

### Downloading the Public GitHub Repository

1.  **Open the Repository in a Web Browser**:

    -   Navigate to the provided URL: [**https://github.com/MatthiasUckert/RpMMA24-Code**](https://github.com/MatthiasUckert/RpMMA24-Code)

2.  **Find the 'Code' Button**:

    -   On the main page of the repository, you'll see a green button labeled "Code".

3.  **Download as ZIP**:

    -   Click on the "Code" button.

    -   In the dropdown menu, you'll see an option to "Download ZIP". Click on this option.

    -   This will start downloading the entire repository as a ZIP file to your computer.

4.  **Extract the ZIP File**:

    -   Once the download is complete, navigate to the location where the ZIP file was saved (typically the "Downloads" folder).

    -   Right-click on the ZIP file (named **`RpMMA24-Code-main.zip`** or similar) and choose the option to "Extract All" (the exact wording might vary depending on your operating system).

    -   Choose a destination folder for the extracted files and click "Extract".

5.  **Open the R Project**:

    -   Navigate to the extracted folder.

    -   Inside, you should find a file with the **`.Rproj`** extension, which represents the R Project.

    -   If you have RStudio installed, you can double-click on this **`.Rproj`** file to open the project in RStudio. If not, you can still navigate through the folder and open individual R scripts using any text editor or R itself.
